# Generated by Django 6.0 on 2026-01-10 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracoes", "0001_initial"),
        ("pacientes", "0002_alter_paciente_atualizado_em"),
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueioAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("hora_inicio", models.TimeField(default="00:00")),
                ("hora_fim", models.TimeField(default="23:59")),
                ("motivo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("feriado", "Feriado"),
                            ("bloqueio", "Bloqueio Manual (Férias/Reunião)"),
                        ],
                        default="bloqueio",
                        max_length=20,
                    ),
                ),
                ("recorrente", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "profissional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profissionais.profissional",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("is_encaixe", models.BooleanField(default=False)),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("aguardando", "Aguardando Atendimento"),
                            ("em_atendimento", "Em Atendimento"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                            ("faltou", "Faltou"),
                        ],
                        default="agendado",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuracoes.convenio",
                    ),
                ),
                (
                    "especialidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profissionais.especialidade",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profissionais.profissional",
                    ),
                ),
            ],
            options={
                "ordering": ["data", "horario"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["agendado", "aguardando", "em_atendimento"])
                        ),
                        fields=("profissional", "data", "horario", "paciente"),
                        name="unique_paciente_horario",
                    )
                ],
            },
        ),
    ]
