# Generated by Django 6.0 on 2026-01-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracoes", "0001_initial"),
        ("pacientes", "0001_initial"),
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("is_encaixe", models.BooleanField(default=False)),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("confirmado", "Confirmado"),
                            ("cancelado", "Cancelado"),
                            ("concluido", "Concluído"),
                        ],
                        default="agendado",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuracoes.convenio",
                    ),
                ),
                (
                    "especialidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profissionais.especialidade",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profissionais.profissional",
                    ),
                ),
            ],
            options={
                "ordering": ["data", "horario"],
            },
        ),
    ]
