# Generated by Django 6.0 on 2026-01-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("agendado", "Agendado"),
                    ("aguardando", "Aguardando Atendimento"),
                    ("em_atendimento", "Em Atendimento"),
                    ("finalizado", "Finalizado"),
                    ("cancelado", "Cancelado"),
                ],
                default="agendado",
                max_length=20,
            ),
        ),
    ]
