# Generated by Django 6.0 on 2026-01-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.convenio'),
        ),
    ]
