# Generated by Django 6.0 on 2026-01-10 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueioAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("hora_inicio", models.TimeField(default="00:00")),
                ("hora_fim", models.TimeField(default="23:59")),
                ("motivo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("feriado", "Feriado"),
                            ("bloqueio", "Bloqueio Manual (Férias/Reunião)"),
                        ],
                        default="bloqueio",
                        max_length=20,
                    ),
                ),
                ("recorrente", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "profissional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profissionais.profissional",
                    ),
                ),
            ],
        ),
    ]
