# Generated by Django 6.0 on 2026-01-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="enviar_whatsapp",
            field=models.BooleanField(default=True, verbose_name="Enviar Confirmação?"),
        ),
    ]
