# Generated by Django 6.0 on 2026-01-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0002_agendamento_enviar_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloqueioagenda",
            name="observacao",
            field=models.TextField(
                blank=True, help_text="Observação para enviar aos pacientes", null=True
            ),
        ),
    ]
