# Generated by Django 6.0 on 2026-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0002_agendamento_atualizado_em_alter_agendamento_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("agendado", "Agendado"),
                    ("aguardando", "Aguardando Atendimento"),
                    ("em_atendimento", "Em Atendimento"),
                    ("finalizado", "Finalizado"),
                    ("cancelado", "Cancelado"),
                    ("faltou", "Faltou"),
                ],
                default="agendado",
                max_length=20,
            ),
        ),
    ]
