# Generated by Django 6.0 on 2026-01-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0003_bloqueioagenda_observacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="lembrete_enviado",
            field=models.BooleanField(
                default=False, verbose_name="Lembrete 24h enviado?"
            ),
        ),
    ]
