# Generated by Django 6.0 on 2026-01-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0004_agendamento_lembrete_enviado"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="bloqueio_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pacientes_cancelados",
                to="agendamento.bloqueioagenda",
            ),
        ),
    ]
