# Generated by Django 6.0 on 2026-01-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0005_agendamento_bloqueio_origem"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="fim_atendimento",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dinheiro", "Dinheiro"),
                    ("pix", "Pix"),
                    ("cartao_credito", "Cartão de Crédito"),
                    ("cartao_debito", "Cartão de Débito"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="horario_chegada",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="inicio_atendimento",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="pago",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="enviar_whatsapp",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="lembrete_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bloqueioagenda",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
