# Generated by Django 6.0 on 2026-01-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0006_agendamento_fim_atendimento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dinheiro", "Dinheiro"),
                    ("pix", "Pix"),
                    ("cartao_credito", "Cartão de Crédito"),
                    ("cartao_debito", "Cartão de Débito"),
                    ("convenio", "Convênio"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
