# Generated by Django 6.0 on 2026-01-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalespecialidade',
            name='sigla_conselho',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
