# Generated by Django 6.0 on 2026-01-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="especialidade",
            name="codigo",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="especialidade",
            name="codigo_visual",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="especialidade",
            name="search_text",
            field=models.CharField(blank=True, db_index=True, max_length=300),
        ),
        migrations.AddField(
            model_name="especialidade",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="especialidade",
            name="nome",
            field=models.CharField(max_length=255),
        ),
    ]
