# Generated by Django 6.0 on 2026-01-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_webhook_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
