# Generated by Django 6.0 on 2026-01-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itens_por_pagina",
                    models.IntegerField(
                        default=10, help_text="Paginação padrão das tabelas"
                    ),
                ),
                (
                    "modo_manutencao",
                    models.BooleanField(
                        default=False, help_text="Bloqueia acesso de não-admins"
                    ),
                ),
                (
                    "max_tentativas_login",
                    models.IntegerField(
                        default=5, help_text="Bloqueia após X tentativas"
                    ),
                ),
                (
                    "tempo_bloqueio_minutos",
                    models.IntegerField(
                        default=15, help_text="Tempo de bloqueio após errar senha"
                    ),
                ),
                (
                    "tempo_sessao_minutos",
                    models.IntegerField(
                        default=60, help_text="Deslogar após inatividade"
                    ),
                ),
                (
                    "janela_agendamento_meses",
                    models.IntegerField(
                        default=6, help_text="Meses à frente liberados na agenda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
            },
        ),
        migrations.CreateModel(
            name="Convenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "percentual_desconto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="DadosClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_fantasia", models.CharField(max_length=255)),
                (
                    "razao_social",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cnpj", models.CharField(blank=True, max_length=18, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="clinica_logos/"
                    ),
                ),
                ("logradouro", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
                ("cep", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
