# Generated by Django 6.0 on 2026-01-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itens_por_pagina",
                    models.IntegerField(
                        default=10, help_text="Paginação padrão das tabelas"
                    ),
                ),
                (
                    "modo_manutencao",
                    models.BooleanField(
                        default=False, help_text="Bloqueia acesso de não-admins"
                    ),
                ),
                (
                    "max_tentativas_login",
                    models.IntegerField(
                        default=5, help_text="Bloqueia após X tentativas"
                    ),
                ),
                (
                    "tempo_bloqueio_minutos",
                    models.IntegerField(
                        default=15, help_text="Tempo de bloqueio após errar senha"
                    ),
                ),
                (
                    "tempo_sessao_minutos",
                    models.IntegerField(
                        default=60, help_text="Deslogar após inatividade"
                    ),
                ),
                (
                    "janela_agendamento_meses",
                    models.IntegerField(
                        default=6, help_text="Meses à frente liberados na agenda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
            },
        ),
    ]
