# Generated by Django 6.0 on 2026-01-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosistema",
            name="enviar_whatsapp_global",
            field=models.BooleanField(
                default=True,
                help_text="Se desmarcado, NENHUMA  mensagem será enviado pelo sistema.",
            ),
        ),
    ]
