# Generated by Django 6.0 on 2026-01-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinica_logos/'),
        ),
    ]
