# Generated by Django 6.0 on 2026-01-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0002_configuracaosistema_enviar_whatsapp_global"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosistema",
            name="data_ultima_execucao_lembrete",
            field=models.DateField(
                blank=True,
                help_text="Data do último disparo automático realizado",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="configuracaosistema",
            name="enviar_wpp_bloqueio",
            field=models.BooleanField(
                default=True, verbose_name="Enviar Aviso de Bloqueio/Cancelamento"
            ),
        ),
        migrations.AddField(
            model_name="configuracaosistema",
            name="enviar_wpp_confirmacao",
            field=models.BooleanField(
                default=True, verbose_name="Enviar Confirmação (Novo Agendamento)"
            ),
        ),
        migrations.AddField(
            model_name="configuracaosistema",
            name="enviar_wpp_lembrete",
            field=models.BooleanField(
                default=True, verbose_name="Enviar Lembrete (Dia Anterior)"
            ),
        ),
        migrations.AddField(
            model_name="configuracaosistema",
            name="horario_disparo_lembrete",
            field=models.TimeField(
                default="08:00", help_text="Horário alvo para o envio automático"
            ),
        ),
    ]
