# Generated by Django 6.0 on 2026-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0003_configuracaosistema_data_ultima_execucao_lembrete_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255)),
                ("principio_ativo", models.CharField(max_length=255)),
                ("apresentacao", models.CharField(blank=True, max_length=255)),
                ("laboratorio", models.CharField(blank=True, max_length=255)),
                ("tarja", models.CharField(blank=True, max_length=100, null=True)),
                ("nome_busca", models.TextField(blank=True)),
                ("situacao", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
