# Generated by Django 6.0 on 2026-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0004_medicamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exame",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo_tuss", models.CharField(db_index=True, max_length=20, unique=True)),
                ("nome", models.CharField(max_length=500)),
                ("tipo", models.CharField(choices=[("Consulta", "Consulta"), ("Exame", "Exame"), ("Procedimento Clinico", "Procedimento Clinico"), ("Cirurgia/Intervencao", "Cirurgia/Intervencao")], default="Exame", max_length=50)),
                ("search_text", models.CharField(db_index=True, max_length=600)),
                ("situacao", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
