# Generated by Django 6.0 on 2026-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0005_exame"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cid",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(db_index=True, max_length=10, unique=True)),
                ("nome", models.CharField(max_length=500)),
                ("search_text", models.CharField(db_index=True, max_length=600)),
                ("situacao", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
    ]
