# Generated by Django 6.0 on 2026-01-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "nome_mae",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome da Mãe",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Feminino", "Feminino"),
                            ("Masculino", "Masculino"),
                            ("Outro", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("cep", models.CharField(blank=True, max_length=20, null=True)),
                ("logradouro", models.CharField(blank=True, max_length=255)),
                ("numero", models.CharField(blank=True, max_length=20)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=2)),
                ("historico_medico", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateField(auto_now=True)),
            ],
        ),
    ]
