# Generated by Django 6.0 on 2026-01-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="prioridade",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Nenhuma"),
                    ("idoso", "Idoso (60+)"),
                    ("gestante", "Gestante / Lactante"),
                    ("cadeirante", "Cadeirante / Mobilidade Reduzida"),
                    ("autista", "Transtorno do Espectro Autista"),
                    ("pcd", "PCD / Deficiência Oculta"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Condição de Prioridade",
            ),
        ),
    ]
