# Generated by Django 6.0 on 2026-01-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="atualizado_em",
            field=models.DateField(auto_now=True),
        ),
    ]
