# Generated by Django 6.0 on 2026-01-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_remove_paciente_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='complemento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(blank=True, help_text='Alergias, doenças prévias, etc.'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, default='87.507-460', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, default='Umuarama', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, default='PR', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='logradouro',
            field=models.CharField(blank=True, default='teste', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, default=2126, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, default='4499999999', max_length=20),
            preserve_default=False,
        ),
    ]
