# Generated by Django 6.0 on 2026-01-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfiloperador",
            name="acesso_cadastros",
            field=models.BooleanField(
                default=False, verbose_name="Acesso a Cadastros Gerais"
            ),
        ),
    ]
