# Generated by Django 6.0 on 2026-01-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens_por_pagina', models.IntegerField(default=15)),
            ],
        ),
        migrations.AddField(
            model_name='perfiloperador',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
