# Generated by Django 6.0 on 2026-01-10 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profissionais", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operador",
            name="profissional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operador_vinculado",
                to="profissionais.profissional",
                verbose_name="Profissional Vinculado",
            ),
        ),
        migrations.AlterField(
            model_name="operador",
            name="acesso_agendamento",
            field=models.BooleanField(
                default=False, verbose_name="Acesso Recepção/Agenda"
            ),
        ),
        migrations.AlterField(
            model_name="operador",
            name="acesso_atendimento",
            field=models.BooleanField(
                default=False, verbose_name="Acesso Atendimento/Prontuário"
            ),
        ),
    ]
