# Generated by Django 6.0 on 2026-01-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_operador_profissional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operador",
            name="acesso_agendamento",
            field=models.BooleanField(
                default=False, verbose_name="Acesso à Recepção/Agenda"
            ),
        ),
        migrations.AlterField(
            model_name="operador",
            name="acesso_atendimento",
            field=models.BooleanField(
                default=False, verbose_name="Acesso Médico/Prontuário"
            ),
        ),
    ]
