# Generated by Django 6.0 on 2026-01-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_operador_acesso_agendamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operador",
            name="force_password_change",
            field=models.BooleanField(
                default=True, verbose_name="Forçar Troca de Senha no Próximo Login"
            ),
        ),
    ]
