# Generated by Django 6.0 on 2026-01-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_operador_force_password_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="Privilegio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=200, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("module_key", models.CharField(max_length=50)),
                ("module_label", models.CharField(max_length=100)),
                ("module_order", models.IntegerField(default=0)),
                ("item_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="operador",
            name="privilegios",
            field=models.ManyToManyField(blank=True, related_name="operadores", to="usuarios.privilegio"),
        ),
    ]
