# Generated by Django 6.0 on 2026-01-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_operador_acesso_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='acesso_agendamento',
            field=models.BooleanField(default=False, verbose_name='Acesso a Recepcao/Agenda'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='acesso_atendimento',
            field=models.BooleanField(default=False, verbose_name='Acesso Medico/Prontuario'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='acesso_configuracoes',
            field=models.BooleanField(default=False, verbose_name='Acesso a Configuracoes do Sistema'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='force_password_change',
            field=models.BooleanField(default=True, verbose_name='Forcar Troca de Senha no Proximo Login'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema Padrao'),
        ),
    ]
