# Generated by Django 6.0 on 2026-01-10 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("cartao_credito", "Cartão de Crédito"),
                            ("cartao_debito", "Cartão de Débito"),
                            ("pix", "Pix"),
                            ("convenio", "Convênio"),
                            ("pendente", "A definir"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("pago", models.BooleanField(default=False)),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "agendamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fatura",
                        to="agendamento.agendamento",
                    ),
                ),
            ],
        ),
    ]
