# Generated by Django 6.0 on 2026-01-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatura",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fatura",
            name="data_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fatura",
            name="data_vencimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fatura",
            name="desconto",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
