# Generated by Django 6.0 on 2026-01-10 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracoes", "0001_initial"),
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Domingo"),
                            (1, "Segunda"),
                            (2, "Terça"),
                            (3, "Quarta"),
                            (4, "Quinta"),
                            (5, "Sexta"),
                            (6, "Sábado"),
                        ]
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "situacao",
                    models.BooleanField(
                        default=True, verbose_name="Situação da Agenda"
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                ("intervalo_minutos", models.IntegerField()),
                ("quantidade_atendimentos", models.IntegerField(default=1)),
                ("tipo", models.CharField(default="padrao", max_length=20)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valor da Consulta",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuracoes.convenio",
                    ),
                ),
                (
                    "especialidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profissionais.especialidade",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profissionais.profissional",
                    ),
                ),
            ],
        ),
    ]
