# Generated by Django 6.0 on 2026-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agendaconfig_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaconfig',
            name='situacao',
            field=models.BooleanField(default=True, verbose_name='Situação da Agenda'),
        ),
    ]
