# Generated by Django 6.0 on 2026-01-18 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.CharField(blank=True, max_length=255)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('altura_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('pressao_sistolica', models.PositiveIntegerField(blank=True, null=True)),
                ('pressao_diastolica', models.PositiveIntegerField(blank=True, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('classificacao_imc', models.CharField(blank=True, max_length=40)),
                ('obesidade_grau', models.CharField(blank=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triagem', to='agendamento.agendamento')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
