# Generated by Django 6.0 on 2026-01-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='medicacoes_em_uso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='historico_relevante',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='historico_flags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='temperatura_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='frequencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='frequencia_respiratoria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='saturacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='glicemia_capilar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
