# Generated by Django 6.0 on 2026-01-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_add_triagem_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='pressao_classificacao',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
